language: php
sudo: false

php:
  - 5.4
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - drush make --prepare-install build-buildthat.make ../vih.dk --yes
  - cd ../vih.dk
  - chmod -R 777 sites/all/modules
  - drush si standard --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="vih.dk" --yes
  - drush cc all --yes
  - cd ../buildthat

script: 
  - test -d ../vih.dk/sites/all/modules/contrib
