language: php
sudo: false

php:
  - 5.6

mysql:
  database: drupal
  username: root
  encoding: utf8

# Cache Composer & Drush directories.
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

before_script:
  - "mysql -e 'create database drupal;'"

  # Install latest Drush 6.
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "drush/drush:6.*"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Build site.
  - drush make --prepare-install build-buildthat.make ../vih.dk --yes
  - cd ../vih.dk
  - chmod -R 777 sites/all/modules
  - drush si standard --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="vih.dk" --yes
  - drush cc all --yes
  - cd ../buildthat

script: 
  - test -d ../vih.dk/sites/all/modules/contrib
